### PR TITLE
Stockchart support

### PR DESCRIPTION
**Pull request by sayo-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/227)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
I was hoping to see this more like we have on Charts 5 with a `timeline` property, like here https://github.com/vaadin/vaadin-charts/blob/5.0/base-chart.html#L139. This way we don't change much our current API.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-:-KzNT35gV22xR0IPmj1E:bs63l59)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-chart.html, line 472 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzNbGyA1Epv7y5jP6Dx:-KzNbGyA1Epv7y5jP6Dy:b-vse7k5) ([raw file](https://github.com/vaadin/vaadin-charts/blob/a1abf68b85fb712a7a33fa579e094db36b5240f2/vaadin-chart.html#L472)):*
> ```HTML
>         __timelineChanged(newValue, oldValue) {
>           if (this._configuration) {
>             this.update(this._configuration, false);
> ```

This is not the same configuration that should be passed over to `update()` method. `_configuration` is the Highcharts instance. Probably we should save the configuration object that is passed to `update` in order to use it here. Also, this method should make sure to use the `<vaadin-charts-series>` configurations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-chart.html, line 380 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzOMHLq5NFPBOdyEWlq:-KzOMHLq5NFPBOdyEWlr:b-bszq14) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c14b18c433e77e8ab5828148aa2bba90988b0ccd/vaadin-chart.html#L380)):*
> ```HTML
>          *    if existing configuration should be discarded.
>          *
>          * @param {String} initialization Optional, 'chart' or 'stockChart'. Defaults to 'chart'.
> ```

This is no longer needed. 

---

*[vaadin-chart.html, line 384 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzOMLYYiNdbm_Bwb4Qq:-KzOMLYYiNdbm_Bwb4Qr:b-j4xge8) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c14b18c433e77e8ab5828148aa2bba90988b0ccd/vaadin-chart.html#L384)):*
> ```HTML
>          * @param {Boolean} timeline Optional, The chart will be a timeline chart if this parameter or the timeline property is true.
>          */
>         update(jsonConfiguration, resetConfiguration, timeline) {
> ```

Do we really need it to add to our API? Then we would have two source of truths, one from `timeline` property and another one from this parameter. What if someone creates the component as `<vaadin-charts timeline>` and then calls `charts.update({}, false, false)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227)*

**Comment by sayo-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-chart.html, line 472 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzNbGyA1Epv7y5jP6Dx:-KzObf-bgtiHccw3JOsW:bt01xxt) ([raw file](https://github.com/vaadin/vaadin-charts/blob/a1abf68b85fb712a7a33fa579e094db36b5240f2/vaadin-chart.html#L472)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

This is not the same configuration that should be passed over to `update()` method. `_configuration` is the Highcharts instance. Probably we should save the configuration object that is passed to `update` in order to use it here. Also, this method should make sure to use the `<vaadin-charts-series>` configurations.
</blockquote></details>

Observer removed until there is a proper design for live timeline changes.

---

*[vaadin-chart.html, line 380 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzOMHLq5NFPBOdyEWlq:-KzObwz_0AiDncbTsuDb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c14b18c433e77e8ab5828148aa2bba90988b0ccd/vaadin-chart.html#L380)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

This is no longer needed. 
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 384 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227#-KzOMLYYiNdbm_Bwb4Qq:-KzOc-fIHsUJ7lIZpK_D:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c14b18c433e77e8ab5828148aa2bba90988b0ccd/vaadin-chart.html#L384)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Do we really need it to add to our API? Then we would have two source of truths, one from `timeline` property and another one from this parameter. What if someone creates the component as `<vaadin-charts timeline>` and then calls `charts.update({}, false, false)`?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227)*

**Comment by DiegoCardoso** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/227)*

**Pull request merged**
