### PR TITLE
CHARTS-642: Title and Subtitle using the high-level Element API

### PR DESCRIPTION
**Pull request by sayo-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/210)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 366 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxrQnMa-mrrm9Z2Vmec:-KxrQnMa-mrrm9Z2Vmed:bbseqlo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/7b5cecb5858efbbc4bbe7eaa6848821282cb67e1/vaadin-chart.html#L366)):*
> ```HTML
>             if (newValue && newValue.length > 0) {
>               if (!this.configuration.subtitle) {
>                 this.configuration.setTitle(null, {text: newValue, y: 38});
> ```

Is there any reason to not use `this.configuration.setSubtitle()` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210)*

**Comment by sayo-vaadin** [comment]
*[vaadin-chart.html, line 366 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxrQnMa-mrrm9Z2Vmec:-KxrXkjrwA_OWYByDprr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/7b5cecb5858efbbc4bbe7eaa6848821282cb67e1/vaadin-chart.html#L366)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Is there any reason to not use `this.configuration.setSubtitle()` here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-chart.html, line 366 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxrQnMa-mrrm9Z2Vmec:-KxsDDX0RGRzAllOHt7P:b-4y2ept) ([raw file](https://github.com/vaadin/vaadin-charts/blob/7b5cecb5858efbbc4bbe7eaa6848821282cb67e1/vaadin-chart.html#L366)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why does it need to also set the `y` value by default?

---

*[vaadin-chart.html, line 355 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxsDOUXnjfDYsTSpoJJ:-KxsDOUXnjfDYsTSpoJK:bo9frcl) ([raw file](https://github.com/vaadin/vaadin-charts/blob/0c6c590ac13900cf1a3afa5389b668121f70ea09/vaadin-chart.html#L355)):*
> ```HTML
> 
>         __updateTitle(newValue) {
>           Polymer.RenderStatus.afterNextRender(this.configuration, () => {
> ```

Does it work if you change it to `berforeNextRender`? 

---

*[vaadin-chart.html, line 363 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxsDVdJSpWig9T7GonL:-KxsDVdJSpWig9T7GonM:b-haojmq) ([raw file](https://github.com/vaadin/vaadin-charts/blob/0c6c590ac13900cf1a3afa5389b668121f70ea09/vaadin-chart.html#L363)):*
> ```HTML
> 
>         __updateSubtitle(newValue) {
>           Polymer.RenderStatus.afterNextRender(this.configuration, () => {
> ```

Same as previous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210)*

**Comment by sayo-vaadin** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-chart.html, line 366 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxrQnMa-mrrm9Z2Vmec:-KxvckOmEVIm4iVrc-_Y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/7b5cecb5858efbbc4bbe7eaa6848821282cb67e1/vaadin-chart.html#L366)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Why does it need to also set the `y` value by default?
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 355 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxsDOUXnjfDYsTSpoJJ:-Kxvclo8mmlV5TbFG3ET:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/0c6c590ac13900cf1a3afa5389b668121f70ea09/vaadin-chart.html#L355)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Does it work if you change it to `berforeNextRender`? 
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 363 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-KxsDVdJSpWig9T7GonL:-KxvcjPJEefBfvpoCxyI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/0c6c590ac13900cf1a3afa5389b668121f70ea09/vaadin-chart.html#L363)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Same as previous.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210)*

**Comment by DiegoCardoso** [comment]
Please, fix the conflicts.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-:-KxwkwmmFSCHNBur6XfK:b3byhii)*

**Comment by sayo-vaadin** [comment]
Done.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210#-:-KxwoA-lSAloIx_IanrH:b-896fix)*

**Comment by DiegoCardoso** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/210)*

**Pull request merged**
