### PR TITLE
Add a demo with vaadin-board

### PR DESCRIPTION
**Pull request by DiegoCardoso**
This is the result of the task to try to find issues with Vaadin Charts sizing task. 

I am not sure about the file location, that's why I didn't add to the demos menu, though it's in the demo folder. Suggestions are welcome.

JIRA: CHARTS-595

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/254)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/flex-container.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254#-L0KZldYaGxMWZl1LbYZ:-L0KZldZQFuhJRPVdVO-:b-p132m1) ([raw file](https://github.com/vaadin/vaadin-charts/blob/db884df7bd613df50f1c67343c6c1fddb07f716b/demo/flex-container.html#L51)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>               <vaadin-chart title="Chart #B1">
>                 <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>               </vaadin-chart>
>               <vaadin-chart title="Chart #B2">
>                 <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>               </vaadin-chart>
</details>

Should this two have double height? is there an issue for it?

---

*[demo/flex-container.html, line 77 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254#-L0KZvrJi4xv9-LW4RvQ:-L0KZvrJi4xv9-LW4RvR:b-944acz) ([raw file](https://github.com/vaadin/vaadin-charts/blob/db884df7bd613df50f1c67343c6c1fddb07f716b/demo/flex-container.html#L77)):*
>                   <vaadin-chart title="Chart #C4" style="height: 250px">
>                     <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>                   </vaadin-chart>

Height is cropping the content and not making the whole charts smaller, is there an issue for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/flex-container.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254#-L0KZldYaGxMWZl1LbYZ:-L0d94bgnZAudQ8CRnl0:b-r4k2ny) ([raw file](https://github.com/vaadin/vaadin-charts/blob/db884df7bd613df50f1c67343c6c1fddb07f716b/demo/flex-container.html#L51)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>               <vaadin-chart title="Chart #B1">
>                 <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>               </vaadin-chart>
>               <vaadin-chart title="Chart #B2">
>                 <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>               </vaadin-chart>

Should this two have double height? is there an issue for it?
</blockquote></details>

Yes. There's this issue https://protools.atlassian.net/browse/CHARTS-706.

---

*[demo/flex-container.html, line 77 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254#-L0KZvrJi4xv9-LW4RvQ:-L0d98czpKLypJckfEnk:bo29i02) ([raw file](https://github.com/vaadin/vaadin-charts/blob/db884df7bd613df50f1c67343c6c1fddb07f716b/demo/flex-container.html#L77)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>                   <vaadin-chart title="Chart #C4" style="height: 250px">
>                     <vaadin-chart-series  values="[1,2,3,4]"></vaadin-chart-series>
>                   </vaadin-chart>

Height is cropping the content and not making the whole charts smaller, is there an issue for it?
</blockquote></details>

I believe is the same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/flex-container.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254#-L0KZldYaGxMWZl1LbYZ:-L0dAbkELYTfMbY6Rz-B:b-1y50yw) ([raw file](https://github.com/vaadin/vaadin-charts/blob/db884df7bd613df50f1c67343c6c1fddb07f716b/demo/flex-container.html#L51)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Yes. There's this issue https://protools.atlassian.net/browse/CHARTS-706.
</blockquote></details>

There's a suggested solution for this on my comment on CHART-595, which is to set `chart` div to `height: 100%`. When I tried this, however, other issues raised, as you can also see on the comment. I don't know how to report these news issues, as they depend on going with that solution or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/254)*

**Pull request merged**
