### PR TITLE
CHARTS-692: Event handling enhancement

### PR DESCRIPTION
**Pull request by oluwasayo**
- Workaround for vaadin-charts-flow because of https://github.com/vaadin/flow/issues/3102
- Support for legend visibility toggle

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/252)

### CODE REVIEW

**Comment by oluwasayo** [comment]
*[vaadin-chart.html, line 23 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0A_AvlinYeKP3vi1ju:-L0E2mZjrEFmpLKCn0BY:b-3yqo7u) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c586021bcafd661f958cdd34733b1042c2d78040/vaadin-chart.html#L23)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> <script src="../highcharts/js/modules/drilldown.js"></script>

why was this needed?
</blockquote></details>

Top-level drilldowns don't display with the styled-mode JS. 
I have reported this issue to highcharts and also submitted a PR that fixes it. 
https://github.com/highcharts/highcharts/issues/7523

Note that the current workaround (not using the styled mode JS) gives wrong drilldown colors but I guess that's better than not having drilldowns display at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252)*

**Comment by DiegoCardoso** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-chart.html, line 23 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0A_AvlinYeKP3vi1ju:-L0JFJAXuLe9eKWY6wpY:bo6cr2h) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c586021bcafd661f958cdd34733b1042c2d78040/vaadin-chart.html#L23)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Top-level drilldowns don't display with the styled-mode JS. 
I have reported this issue to highcharts and also submitted a PR that fixes it. 
https://github.com/highcharts/highcharts/issues/7523

Note that the current workaround (not using the styled mode JS) gives wrong drilldown colors but I guess that's better than not having drilldowns display at all.
</blockquote></details>

I have mixed feelings about this. Though it fixes the issue, it mixes styled and classic mode, as pointed out as "wrong" on the issue you linked. Maybe we can leave this as it was and wait for their fix and create another PR with that.

---

*[vaadin-chart.html, line 693 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JF0lzYnRrzPqRVtdp:-L0JF0lzYnRrzPqRVtdq:bkpkt7j) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L693)):*
> ```HTML
> 
>                 // Workaround for vaadin-charts-flow because of https://github.com/vaadin/flow/issues/3102
>                 if (event.type == 'selection') {
> ```

Please, prefer to use strict comparison.

---

*[vaadin-chart.html, line 703 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JFDgvJoaIOqfT6se9:-L0JFDgwIpsBZyUdd9_2:b2nreh6) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L703)):*
> ```HTML
>                   }
>                 }
>                 if (event.type == 'click') {
> ```

Same as above.

---

*[vaadin-chart.html, line 714 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JFHhuU0FnEQwgGPgV:-L0JFHhuU0FnEQwgGPgW:b2nreh6) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L714)):*
> ```HTML
>                 self.dispatchEvent(new CustomEvent(eventList[key], customEvent));
> 
>                 if (event.type == 'legendItemClick' && chart['_seriesVisibilityTogglingDisabled']) {
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252)*

**Comment by oluwasayo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-chart.html, line 23 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0A_AvlinYeKP3vi1ju:-L0KCZQwa9_cELva98f_:b7yh2wc) ([raw file](https://github.com/vaadin/vaadin-charts/blob/c586021bcafd661f958cdd34733b1042c2d78040/vaadin-chart.html#L23)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

I have mixed feelings about this. Though it fixes the issue, it mixes styled and classic mode, as pointed out as "wrong" on the issue you linked. Maybe we can leave this as it was and wait for their fix and create another PR with that.
</blockquote></details>

New workaround implemented as discussed

---

*[vaadin-chart.html, line 693 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JF0lzYnRrzPqRVtdp:-L0KCaynrXwaYikL4QZj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L693)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Please, prefer to use strict comparison.
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 703 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JFDgvJoaIOqfT6se9:-L0KCbW1WsW8qymahBMA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L703)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 714 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252#-L0JFHhuU0FnEQwgGPgV:-L0KCcEMo4kKbQ_NAVnF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/50573d6d7a624399363abaf1a1fab6c19b9aeba5/vaadin-chart.html#L714)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/252)*

**Pull request merged**
