### PR TITLE
Use chart-loaded event on angular 2 tests. 

### PR DESCRIPTION
**Pull request by samiheikki**
Use chart-loaded event on angular 2 tests. importReady eventEmitter to private.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/107)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/107)*

**Comment by rogozinds** [comment]
Can we now remove setTimeouts from chart-angular2-test.html? Basically now the testmethod will run after chart is created, so no need in it?
I"ve tried -it works.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/107#-:-KFx80ZvD0wNl_zwqh3D:-172641444)*

**Comment by rogozinds** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/107)*

**Comment by samiheikki** [comment]
Good point. I'll change it.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/107#-:-KFx8hoyRtqP7DXPvE82:208524625)*

**Pull request closed without merging**
