### PR TITLE
Support chart3d attribute

### PR DESCRIPTION
**Pull request by alexberazouski**
Added 3D column demo and test

CHARTS-654

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)

### CODE REVIEW

**Comment by oluwasayo** [comment]
*[vaadin-chart.html, line 390 at r3](https://reviewable.io/reviews/vaadin/vaadin-charts/351#-LD0dxhMBsBFP17r-kNM:-LD0dxhMBsBFP17r-kNN:b9qude2) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fc00bf0833a9fa498358b97ccd305e241dff236b/vaadin-chart.html#L390)):*
> ```HTML
>              * Some display angles are added by default to the "chart.options3d" (`{alpha: 15, beta: 15, depth: 50}`).
>              * 3D display options can be modified via additionalOptions.
>              * 3D is supported by Column, Pie and Scatter3D charts.
> ```

Also works with bar charts

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Comment by oluwasayo** [comment]
*[demo/index.html, line 255 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/351#-LCiaApp1_aNR6l4govU:-LD0erGH59PEz6lWYcX0:bx7ncuz) ([raw file](https://github.com/vaadin/vaadin-charts/blob/15865dadf39603d0f7d81a6b0abf589ba9651b1f/demo/index.html#L255)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

Using chart3d makes sense with setting some options3d angles. Otherwise there won't be any 3D effect
</blockquote></details>

Why do we need additional configuration if `chart3d` sets reasonable defaults?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart.html, line 390 at r3](https://reviewable.io/reviews/vaadin/vaadin-charts/351#-LD0dxhMBsBFP17r-kNM:-LD0t33L2P77u54ZMq5w:b-3cm6mq) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fc00bf0833a9fa498358b97ccd305e241dff236b/vaadin-chart.html#L390)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Also works with bar charts
</blockquote></details>

Added bar to the list.

---

*[demo/index.html, line 255 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/351#-LCiaApp1_aNR6l4govU:-LD0oqmD8Wfjg6SdZ5Qm:b-m0mdiy) ([raw file](https://github.com/vaadin/vaadin-charts/blob/15865dadf39603d0f7d81a6b0abf589ba9651b1f/demo/index.html#L255)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Why do we need additional configuration if `chart3d` sets reasonable defaults?
</blockquote></details>

For pie, they look quite from a top view, so that's why I decided to add some different values in this case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Comment by oluwasayo** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Comment by oluwasayo** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/351)*

**Pull request merged**
