### PR TITLE
Empty-text property on vaadin-chart

### LINKED ISSUE #355: Allow setting empty-text for vaadin-chart element using Element API

### PR DESCRIPTION
**Pull request by oluwasayo**
Fixes #355

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/357)

### CODE REVIEW

**Comment by alexberazouski** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[vaadin-chart.html, line 879 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/357#-LDg6_yR4b-t3E9E4_Ck:-LDg6_yR4b-t3E9E4_Cl:b-6issgw) ([raw file](https://github.com/vaadin/vaadin-charts/blob/257b63e0353f1f58184648d35a840951dab34a46/vaadin-chart.html#L879)):*
> ```HTML
>           // when all points are removed from all series without removing any series.
>           const isEmpty = this.configuration.series.length === 0 ||
>               this.configuration.series.map(e => e.values.length === 0).reduce((e1, e2) => e1 && e2, true);
> ```

`e.values` is undefined

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/357)*

**Comment by oluwasayo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 879 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/357#-LDg6_yR4b-t3E9E4_Ck:-LDgGVb_4A5mqPkKbdJz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/257b63e0353f1f58184648d35a840951dab34a46/vaadin-chart.html#L879)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

`e.values` is undefined
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/357)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/357#-:-LDlGBDy8rVuY1q5t7yR:bnfp4nl)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/357#-:-LDlaw661fY17fOPjMsM:bnfp4nl)*

**Pull request merged**
