### PR TITLE
Change from Highcharts to Highstock (CHARTS-300) 

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/65)

### CODE REVIEW

**Comment by jarski** [comment]
Write a test for timeline (check that HighStock is created instead of HighCharts)

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[chart-behavior.html, line 334 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65#-K91258d_GQmcdG4S6XF:-K91258d_GQmcdG4S6XG:423151957) ([raw file](https://github.com/vaadin/vaadin-charts/blob/bfe943b52a037ab48ab654b5488e53519de8fac6/chart-behavior.html#L334)):*
Add comment here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65#-:-K914Oit-Ierl-U2clAD:257006801)*

**Comment by alvarezguille** [comment]
Done

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65#-:-K91AVwjbuHPfnyL4EQq:676635175)*

**Comment by jarski** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[chart-behavior.html, line 334 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65#-K91258d_GQmcdG4S6XF:-K91CJiKPuAQKFSJAZDw:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/bfe943b52a037ab48ab654b5488e53519de8fac6/chart-behavior.html#L334)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/65)*

**Pull request merged**
