### PR TITLE
Support stack and stacking properties for series

### PR DESCRIPTION
**Pull request by alexberazouski**
CHARTS-661

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349)

### CODE REVIEW

**Comment by oluwasayo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349)*

**Comment by DiegoCardoso** [comment]
Needs to update `analysis.json`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[vaadin-chart-series.html, line 409 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/349#-LCiEloIBL_Oc1LYCTN3:-LCiEloIBL_Oc1LYCTN4:bb89huw) ([raw file](https://github.com/vaadin/vaadin-charts/blob/bfcdb97076998c62e73d3ad28ee9e65bf617429f/vaadin-chart-series.html#L409)):*
> ```HTML
>             return false;
>           }
>           return true;          
> ```

Nitpick: trailing whitespace.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349#-:-LCiEvW75PxNIa9gAyh2:b-k7181q)*

**Comment by alexberazouski** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart-series.html, line 409 at r1](https://reviewable.io/reviews/vaadin/vaadin-charts/349#-LCiEloIBL_Oc1LYCTN3:-LCiHhtr0Yc_H2nyvYfd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/bfcdb97076998c62e73d3ad28ee9e65bf617429f/vaadin-chart-series.html#L409)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Nitpick: trailing whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349)*

**Comment by oluwasayo** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/349)*

**Pull request merged**
