### PR TITLE
Added js API and updated demo, docs and test

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/191)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
*[demo/js-api.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191#-KutL86benLTFsPtRcdC:-KutL86benLTFsPtRcdD:blcfcy9) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d10e9b6f48dcadedeceb7d73f9d13086433ef206/demo/js-api.html#L9)):*
> ```HTML
>   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
> 
>   <title>vaadin-chart Advanced Examples</title>
> ```

Title can be more specific.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191)*

**Comment by alvarezguille** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/js-api.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191#-KutL86benLTFsPtRcdC:-KutWAoqjU6WWoDcOJZG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d10e9b6f48dcadedeceb7d73f9d13086433ef206/demo/js-api.html#L9)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Title can be more specific.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191)*

**Comment by sayo-vaadin** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191#-:-KutWOUXLCqQrBCPqsiz:bnfp4nl)*

**Comment by sayo-vaadin** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/191)*

**Pull request merged**
