### PR TITLE
Add more chart types

### LINKED ISSUE #198: Some chart types are unusable due to missing imports (6.0-preview)
I tried to use a solidgauge chart type, but that failed because highcharts solid-gauge.js is not imported and there is no clear way to add it yourself.

I suspect funnel at least is similar as it also has an own js file.

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Add support to more chart types as seen at vaadin-charts 5.

Known issue:
- Colors are not working properly on some charts

Fixes #198
JIRA: CHARTS-619

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/204)

### CODE REVIEW

**Comment by johannesh2** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/204)*

**Comment by Peppe** [comment]
Please look at this closer before you merge. 

You are adding: 
highstock.js, highcharts-more.js, highcharts-3d.js, data.js, drilldown.js, exporting.js, funnel.js, heatmap.js, solid-gauge.js, treemap.js

According to https://code.highcharts.com/, under Highstock - Style by JavaScript there are only available:
highstock.js, highcharts-more.js, exporting.js, drilldown.js, solid-gauge.js

The list is much shorter. I think that the reason is that those that you have are HighCharts dependencies and highcharts-3d, data, funnel, heatmap and treemap is already embedded into HighStock by default, and those scripts will never be used.

We have a problem in Charts 5 with the size that has to be downloaded by the browser, so please try to minimize the amount of imports, especially if they are not used in the end. Also for the others it would be important to see if we need them before importing them. Now every linechart will also gauges and drilldowns and exports.

@johannesh2 @DiegoCardoso

**Comment by johannesh2** [comment]
Valid points Peppe. We should not import duplicate things. However, let's keep the further optimization as a separate issue.

**Comment by DiegoCardoso** [comment]
I also tried to remove the files that are not under Highstock list to see if it would work and I got error about missing chart type. They started working again once I added the import back.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/204#-:-KwEwENjLzTnV1cgXcSz:bnqjq5s)*

**Comment by johannesh2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/204)*

**Pull request merged**
