### PR TITLE
Remove Angular2 and React support, closes #COM-24

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/145)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZanVr3hhdGjIPPayf6:-KZanVr3hhdGjIPPayf7:b-wieaxd) (no related file):*
* config/default.json
* tasks/cdn.js
* tasks/zip.js

 seems to still contain some React/Angular stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145)*

**Comment by Artur-** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2wWd2hE5yX2l9AfG:-KZb2wWd2hE5yX2l9AfH:bjjfp52) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L10)):*
> ```JSON
>   "devDependencies": {
>     "bower": "^1.4.1",
>     "browserify": "^13.0.1",
> ```

is this react related?

---

*[package.json, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2hvyb2Lcrnz8DEjm:-KZb2hvyb2Lcrnz8DEjn:buf1idv) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L26)):*
> ```JSON
>     "gulp-zip": "^3.2.0",
>     "lodash": "^3.9.1",
>     "reflect-metadata": "^0.1.3",
> ```

is this angular2 related?

---

*[package.json, line 28 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2avbiqz2RPOvIIm-:-KZb2avbiqz2RPOvIIm0:bjjfp52) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L28)):*
> ```JSON
>     "reflect-metadata": "^0.1.3",
>     "web-component-tester": "^3.3.9",
>     "yargs": "^3.9.1"
> ```

is this react related?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145)*

**Comment by rogozinds** [comment]
Review status: 24 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2wWd2hE5yX2l9AfG:-KZb53XKBTCQgvx-CRu7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L10)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this react related?
</blockquote></details>

Done.

---

*[package.json, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2hvyb2Lcrnz8DEjm:-KZb54GhYzg_DNOkwNDt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L26)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this angular2 related?
</blockquote></details>

Done.

---

*[package.json, line 28 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145#-KZb2avbiqz2RPOvIIm-:-KZb54j_1IZeVgN02Y6y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9eacf8634be985228974856523e2a653a25a1309/package.json#L28)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this react related?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/145)*

**Pull request merged**
