### PR TITLE
Adding description file for Vaadin Directory

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/336)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Do you know why there's no image if I open https://github.com/vaadin/vaadin-charts/blob/directory-description/vaadin-directory-description.md?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/336#-:-LB_MNTI1vk8gGAXGbQs:b412ruj)*

**Comment by manolo** [comment]
Because it's not in master yet. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/336#-:-LB_X82xAnDR_BAFnb3d:b37k2zk)*

**Comment by DiegoCardoso** [comment]
Are you talking about the image or the md file? Beause the image is (https://raw.githubusercontent.com/vaadin/vaadin-charts/master/screenshot.png).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/336#-:-LB_ZV_T0UMOTMYADorH:bc7sm2l)*

**Comment by manolo** [comment]
Fixed, a missing quote.
For some reason it was not failing in asciidoc conversor and md editor.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/336#-:-LB_dL6WDGvS2cnmCE2x:b-xsqwv8)*

**Pull request merged**
