### PR TITLE
Task/convert vaadin charts

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Convert each of Vaadin Charts to Polymer 2 class

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/157)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 16 of 28 files at r1, 9 of 9 files at r2.
Review status: 25 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-sparkline.html, line 55 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157#-KjHSHtqvavbf2KUJEWC:-KjHSHtqvavbf2KUJEWD:bdpf742) ([raw file](https://github.com/vaadin/vaadin-charts/blob/58ab18221bd3097e6ce7cec31760c03d0c70a4d6/vaadin-sparkline.html#L55)):*
> line-color="#FFFFFF"

where does this come from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157)*

**Comment by DiegoCardoso** [comment]
*[vaadin-sparkline.html, line 55 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157#-KjHSHtqvavbf2KUJEWC:-KjHUHu3emNr-iKjrnE1:b-bk3zgm) ([raw file](https://github.com/vaadin/vaadin-charts/blob/58ab18221bd3097e6ce7cec31760c03d0c70a4d6/vaadin-sparkline.html#L55)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> line-color="#FFFFFF"

where does this come from?
</blockquote></details>

I needed to make the sparkline test pass in order to see if the migration was ok and added that to do so. Probably I shouldn't have committed that change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 28 files at r1, 2 of 3 files at r3.
Review status: 28 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/157)*

**Pull request merged**
