### PR TITLE
React component to support Charts usage in React

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/123)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Looks good, didn't check every detail yet. 
But have some initial comments:
* remove old dependencies to react from bower.json
* update gulp scripts to include new 'directive' in cdn and zip folder for stage task
* att enumeration in index.js is something I don't want to maintain, we can discuss details

That's all for now

<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> #### React component to support Charts usage in React
</details>


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-:-KIC4MKB-tIvMHTGBTJG:2068421269)*

**Comment by samiheikki** [comment]
- Removed old react dependency
- Updated gulp scripts to include react 'directive'

<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> Looks good, didn't check every detail yet. 
> But have some initial comments:
> * remove old dependencies to react from bower.json
> * update gulp scripts to include new 'directive' in cdn and zip folder for stage task
> * att enumeration in index.js is something I don't want to maintain, we can discuss details
> 
> That's all for now
</details>


---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-:-KICmBy4YwL06ghqbaXl:649975042)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 7 files at r1, 4 of 4 files at r2.
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[react/index.js, line 212 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIRnzzXkeVgseqLPKD_:-KIRnzzXkeVgseqLPKDa:1360373096) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf97c2cf6bc7b45bfd02fd5e5e0da200768331f/react/index.js#L212)):*
> ```JavaScript
>  *  Array of custom attributes used in vaadin-charts
>  **/
> var attributes = ['active-axis-label-style', 'active-color', 'active-data-label-style', 'adapt-to-updated-data', 'align', 'align-ticks', 'all-buttons-enabled', 'allow-decimals', 'allow-html', 'allow-overlap', 'allow-point-drilldown', 'allow-point-select', 'alpha', 'alternate-grid-color', 'animation', 'approximation', 'arrow-size', 'attr', 'attributes', 'auto-rotation', 'auto-rotation-limit', 'back', 'background', 'background-color', 'bar-background-color', 'bar-border-color', 'bar-border-radius', 'bar-border-width', 'base-series', 'beta', 'border-color', 'border-radius', 'border-width', 'bottom', 'break-size', 'breaks', 'button-arrow-color', 'button-background-color', 'button-border-color', 'button-border-radius', 'button-border-width', 'button-options', 'button-spacing', 'button-theme', 'buttons', 'categories', 'ceiling', 'center', 'change-decimals', 'chart', 'chart-frame', 'chart-options', 'chart-style', 'chart-title', 'class-name', 'color', 'columns', 'compare', 'connect-ends', 'connect-nulls', 'context-button', 'crop', 'crop-threshold', 'crosshair', 'crosshairs', 'csv', 'cursor', 'dash-style', 'data', 'data-grouping', 'data-labels', 'date-format', 'date-time-label-formats', 'decimal-point', 'default-series-type', 'defer', 'depth', 'distance', 'drill-up-button', 'drilldown', 'enable-mouse-tracking', 'enabled', 'end-angle', 'end-column', 'end-on-tick', 'end-row', 'fallback-to-export-server', 'filename', 'fill-color', 'fill-opacity', 'first-row-as-names', 'floating', 'floor', 'follow-pointer', 'follow-touch-move', 'footer-format', 'forced', 'form-attributes', 'format', 'from', 'gap-size', 'get-extremes-from-all', 'google-spreadsheet-key', 'google-spreadsheet-worksheet', 'grid-line-color', 'grid-line-dash-style', 'grid-line-width', 'grid-zIndex', 'group-pixel-width', 'halo', 'handles', 'header-format', 'height', 'hide-delay', 'hide-duration', 'hover', 'href', 'html', 'id', 'ignore-hidden-series', 'inactive-color', 'index', 'input-box-border-color', 'input-box-height', 'input-box-style', 'input-box-width', 'input-date-format', 'input-edit-date-format', 'input-enabled', 'input-position', 'input-style', 'inside', 'inverted', 'item-delimiter', 'item-distance', 'item-hidden-style', 'item-hover-style', 'item-margin-bottom', 'item-margin-top', 'item-style', 'item-width', 'items', 'keys', 'label', 'label-format', 'label-style', 'labels', 'layout', 'legend-index', 'line-color', 'line-delimiter', 'line-height', 'line-width', 'line-width-plus', 'linecap', 'linked-to', 'live-redraw', 'margin', 'margin-bottom', 'margin-left', 'margin-right', 'margin-top', 'marker', 'mask-fill', 'mask-inside', 'max', 'max-height', 'max-padding', 'max-stagger-lines', 'max-zoom', 'menu-item-hover-style', 'menu-item-style', 'menu-items', 'menu-style', 'min', 'min-padding', 'min-range', 'min-tick-interval', 'min-width', 'minor-grid-line-color', 'minor-grid-line-dash-style', 'minor-grid-line-width', 'minor-tick-color', 'minor-tick-interval', 'minor-tick-length', 'minor-tick-position', 'minor-tick-width', 'name', 'navigation', 'negative-color', 'negative-fill-color', 'observers', 'offset', 'opacity', 'opposite', 'options3d', 'ordinal', 'outline-color', 'outline-width', 'overflow', 'padding', 'pan-key', 'panning', 'pinch-type', 'plot-background-color', 'plot-background-image', 'plot-bands', 'plot-border-color', 'plot-border-width', 'plot-lines', 'plot-shadow', 'point', 'point-format', 'point-interval', 'point-interval-unit', 'point-placement', 'point-range', 'point-start', 'polar', 'position', 'radius', 'radius-plus', 'range', 'reflow', 'relative-to', 'render-to', 'repeat', 'reserve-space', 'reset-zoom-button', 'reversed', 'rifle-color', 'rotation', 'rows', 'rtl', 'scale', 'select', 'selected', 'selection-marker-fill', 'series', 'series-mapping', 'shadow', 'shape', 'shared', 'show-axes', 'show-checkbox', 'show-duration', 'show-empty', 'show-first-label', 'show-in-legend', 'show-last-label', 'side', 'size', 'smoothed', 'snap', 'soft-threshold', 'source-height', 'source-width', 'spacing', 'spacing-bottom', 'spacing-left', 'spacing-right', 'spacing-top', 'stack', 'stacking', 'stagger-lines', 'start-angle', 'start-column', 'start-of-week', 'start-on-tick', 'start-row', 'states', 'step', 'sticky-tracking', 'switch-rows-and-columns', 'symbol', 'symbol-fill', 'symbol-height', 'symbol-padding', 'symbol-radius', 'symbol-size', 'symbol-stroke', 'symbol-stroke-width', 'symbol-width', 'symbol-x', 'symbol-y', 'table', 'text', 'text-align', 'theme', 'threshold', 'tick-amount', 'tick-color', 'tick-interval', 'tick-length', 'tick-pixel-interval', 'tick-position', 'tick-positions', 'tick-width', 'tickmark-placement', 'timeline', 'to', 'tooltip', 'track-background-color', 'track-border-color', 'track-border-radius', 'track-border-width', 'track-by-area', 'turbo-threshold', 'type', 'units', 'url', 'use-html', 'value', 'value-decimals', 'value-prefix', 'value-suffix', 'vertical-align', 'view-distance', 'visible', 'width', 'x', 'x-axis', 'x-date-format', 'y', 'y-axis', 'z-index', 'zone-axis', 'zones', 'zoom-type'];
> ```

is there any possibility this can be avoided? I think it's worth the research
otherwise the generation of this should also be reviewed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by samiheikki** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[react/index.js, line 212 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIRnzzXkeVgseqLPKD_:-KISNJ0OeAIlaJJv-f0r:-967475887) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf97c2cf6bc7b45bfd02fd5e5e0da200768331f/react/index.js#L212)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> is there any possibility this can be avoided? I think it's worth the research
> otherwise the generation of this should also be reviewed
</details>
Did not find any way of avoiding this. Not possible of accessing DOM element properties. I think we need some generator for creating the attributes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by samiheikki** [comment]
Review status: 4 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[react/index.js, line 212 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIRnzzXkeVgseqLPKD_:-KIXdIM4tyr8qqnF63ZI:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf97c2cf6bc7b45bfd02fd5e5e0da200768331f/react/index.js#L212)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Did not find any way of avoiding this. Not possible of accessing DOM element properties. I think we need some generator for creating the attributes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 7 files at r1, 3 of 4 files at r4, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by alvarezguille** [comment]
just noticed an "is" property almost everywhere in _chartConf might not be related though

<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> - Removed old react dependency
> - Updated gulp scripts to include react 'directive'
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-:-KIXvvASj3iYSac3LQ6k:1021821186)*

**Comment by samiheikki** [comment]
https://facebook.github.io/react/docs/jsx-gotchas.html#custom-html-attributes only thing I discovered about `is` attribute in React.

<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> just noticed an "is" property almost everywhere in _chartConf might not be related though
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-:-KIaucIZbUX9hQatawVr:65902640)*

**Comment by rogozinds** [comment]
Reviewed 2 of 7 files at r1, 2 of 4 files at r2, 2 of 3 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[react/index.js, line 116 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIavGHyPLGDTZm15PGa:-KIavGHyPLGDTZm15PGb:1260184421) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L116)):*
> ```JavaScript
>     ReactInjection.DOMProperty.injectDOMPropertyConfig({
>         isCustomAttribute: function(name) {
>             return name !== 'children';
> ```

This is an open question can we actually do that? Noone has any clue why react is ignoring non-default attributes by default. I bet they are doing it for some important reason. Probably it's somehow related to partial update of the actual dom. So I'm worry that if we do that change, there will be an impact on performance on real apps with complex DOM. And as far as these settings are global, it's an impact not only our part, but the whole application.

---

*[react/index.js, line 149 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIakA7cdV-844GjlJGI:-KIakA7cdV-844GjlJGJ:279743045) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L149)):*
> ```JavaScript
>   }
> } else {
>   document.addEventListener('WebComponentsReady', function() {
> ```

Is this one needed? In the begining Polymer=global.polymer? When Polymer will be undefined?

---

*[react/index.js, line 160 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIaw8K9jrZrgpxWOLKj:-KIaw8K9jrZrgpxWOLKk:1945962154) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L160)):*
> ```JavaScript
> /**
>  *  Name of the chart events to add to the configuration and its corresponding event for the chart element
>  **/
> ```

We need to remember to update it when new events are introduced

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[react/index.js, line 116 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIavGHyPLGDTZm15PGa:-KIax5FiqYH-t_YYe-34:-262406178) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L116)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> This is an open question can we actually do that? Noone has any clue why react is ignoring non-default attributes by default. I bet they are doing it for some important reason. Probably it's somehow related to partial update of the actual dom. So I'm worry that if we do that change, there will be an impact on performance on real apps with complex DOM. And as far as these settings are global, it's an impact not only our part, but the whole application.
</details>
Good point.  I'll try to find someone to answer this question.

---

*[react/index.js, line 149 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIakA7cdV-844GjlJGI:-KIaxYgQw8jq0Zb3NxhN:-2092148046) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L149)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> Is this one needed? In the begining Polymer=global.polymer? When Polymer will be undefined?
</details>
In browsers that require polyfill. Bundled javascript should be added without `webComponentsReady` eventListener.

---

*[react/index.js, line 160 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIaw8K9jrZrgpxWOLKj:-KIayFHNREQpdF6mjE6X:677251276) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L160)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> We need to remember to update it when new events are introduced
</details>
Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[react/index.js, line 116 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIavGHyPLGDTZm15PGa:-KIbEkjvPUeRDv7M2YN3:-274239080) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L116)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Good point.  I'll try to find someone to answer this question.
</details>
http://stackoverflow.com/questions/37431456/custom-attributes-in-react

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Comment by rogozinds** [comment]
:lgtm:

<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> https://facebook.github.io/react/docs/jsx-gotchas.html#custom-html-attributes only thing I discovered about `is` attribute in React.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-:-KIbIFSxH6tsogNjqqzG:1417088721)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[react/index.js, line 116 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123#-KIavGHyPLGDTZm15PGa:-KIbrP9JTeNADjA0oVxY:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/73890852bb0ebff22a8508e403b4f4e55d31eb93/react/index.js#L116)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> http://stackoverflow.com/questions/37431456/custom-attributes-in-react
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/123)*

**Pull request merged**
