### PR TITLE
Added js JSON API and updated demo, docs and test

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/192)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart.html, line 227 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv0y9mPb0pZd942p4NY:-Kv0y9mPb0pZd942p4NZ:bh6xcge) ([raw file](https://github.com/vaadin/vaadin-charts/blob/f0637e06f28e8cba48700a049932925bd3372ab1/vaadin-chart.html#L227)):*
> ```HTML
>          *    if existing configuration should be discarded. Defaults to `undefined`.
>         */
>         update(jsonConfiguration, initialConfig) {
> ```

I don't know if `initialConfig` is a good name for this parameter. Something like `resetConfig` might communicate better what this parameter is doing. 
Also, I don't know if we could add a default value here, so in the docs we could say _"Defaults to `false`"_ instead of `undefined`.

---

*[test/js-json-api-chart-test.html, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv0xvkLQ2XZj-LKzUTo:-Kv0xvkMzJiO-UqA1vXb:b-e0cp4m) ([raw file](https://github.com/vaadin/vaadin-charts/blob/f0637e06f28e8cba48700a049932925bd3372ab1/test/js-json-api-chart-test.html#L95)):*
> ```HTML
>       });
> 
>       it('should have default title', function(done) {
> ```

Could you add to description of the test that you are forcing it to reset the config?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by alvarezguille** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart.html, line 227 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv0y9mPb0pZd942p4NY:-Kv183HPleDM0VWA_6kM:bz869b6) ([raw file](https://github.com/vaadin/vaadin-charts/blob/f0637e06f28e8cba48700a049932925bd3372ab1/vaadin-chart.html#L227)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

I don't know if `initialConfig` is a good name for this parameter. Something like `resetConfig` might communicate better what this parameter is doing. 
Also, I don't know if we could add a default value here, so in the docs we could say _"Defaults to `false`"_ instead of `undefined`.
</blockquote></details>

Renamed to resetConfiguration, and removed the default value as it's Optional

---

*[test/js-json-api-chart-test.html, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv0xvkLQ2XZj-LKzUTo:-Kv183yRn1bUvM2nIX2h:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/f0637e06f28e8cba48700a049932925bd3372ab1/test/js-json-api-chart-test.html#L95)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Could you add to description of the test that you are forcing it to reset the config?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 247 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv1Xf1xgXjZ_Ny38XFP:-Kv1Xf1xgXjZ_Ny38XFQ:b-bzgqx4) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d2e403488632bb9650cbd96d20898ea910c25309/vaadin-chart.html#L247)):*
> ```HTML
>         }
> 
>         _addSeries(series) {
> ```

I guess this should clear the current series list before adding the new one. For instance, if I have two series, I am not able to update in order to keep only one of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by alvarezguille** [comment]
*[vaadin-chart.html, line 247 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv1Xf1xgXjZ_Ny38XFP:-Kv1acrShLY8UlfC5ceT:bbj1xdq) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d2e403488632bb9650cbd96d20898ea910c25309/vaadin-chart.html#L247)):*
I think that `js API` should be used for removing series, it's not possible to know which series should be removed or if the update should go to the first or second series. 
Removing all and drawing with new configuration would be like a reset of the series, and old previous config will be lost.
Design doc says:
>Note that this must not overwrite current configuration but only apply the changes in here on top of what you have previously configured in some way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 247 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv1Xf1xgXjZ_Ny38XFP:-Kv1q_VMqMiQsn9rlDRU:bgk3h9j) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d2e403488632bb9650cbd96d20898ea910c25309/vaadin-chart.html#L247)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

I think that `js API` should be used for removing series, it's not possible to know which series should be removed or if the update should go to the first or second series. 
Removing all and drawing with new configuration would be like a reset of the series, and old previous config will be lost.
Design doc says:
>Note that this must not overwrite current configuration but only apply the changes in here on top of what you have previously configured in some way

</blockquote></details>

But this is not keeping the previous config either. I think  the way it is now might lead to unexpected results, like the example I gave before. If you have two series with different configurations and want to keep only the second one, the result would be two series with the first one being a merge with the previous series.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 247 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-Kv1Xf1xgXjZ_Ny38XFP:-Kv21pL2j5Y4rhz-fHqw:bewkk77) ([raw file](https://github.com/vaadin/vaadin-charts/blob/d2e403488632bb9650cbd96d20898ea910c25309/vaadin-chart.html#L247)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

But this is not keeping the previous config either. I think  the way it is now might lead to unexpected results, like the example I gave before. If you have two series with different configurations and want to keep only the second one, the result would be two series with the first one being a merge with the previous series.
</blockquote></details>

After debating over this with @alvarezguille about how this should be as design points out and that would be hard to define which series should be updated. Also, we should add to docs how to handle update on specific series with JSON API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/192#-:-Kv2IvM_RqNVqi4k-949:bnfp4nl)*

**Pull request merged**
