### PR TITLE
Prevent chart from growing on window resize

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Chart is growing on resize events if container height is not explicitly defined. This is related with a Highcharts issue on styled mode (https://github.com/highcharts/highcharts/issues/7494).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/247)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
*[vaadin-chart.html, line 614 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247#-L-kBjZzhjOxxkE3CT7Y:-L-kBjZzhjOxxkE3CT7Z:b32vjv) ([raw file](https://github.com/vaadin/vaadin-charts/blob/57bf523553205dd9556864b2ebb445fa153f9433/vaadin-chart.html#L614)):*
> ```HTML
>             if (!this._dirty || resetConfiguration) {
>               const initialOptions = Object.assign({}, this.options, this._jsonConfigurationBuffer);
>               
> ```

:p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 614 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247#-L-kBjZzhjOxxkE3CT7Y:-L-kDGzm_95a3Csp_AIf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/57bf523553205dd9556864b2ebb445fa153f9433/vaadin-chart.html#L614)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

:p
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247)*

**Comment by sayo-vaadin** [comment]
*[vaadin-chart.html, line 557 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247#-L-kDYgJNPZSQs6ptrM1:-L-kDYgJNPZSQs6ptrM2:b-m5b69y) ([raw file](https://github.com/vaadin/vaadin-charts/blob/3e650769c035781771034308606c7c5fe2712758/vaadin-chart.html#L557)):*
> ```HTML
>             this._configuration = Highcharts.chart(this.$.chart, options);
>           }
>           // Workaround for highcharts#7494 to prevent chart growing on window resize
> ```

Do we need a JIRA ticket to track this? @johannesh2 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247)*

**Comment by sayo-vaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/247#-:-L-kECjeme90l9DxdHbe:bnfp4nl)*

**Pull request merged**
