### PR TITLE
Fix parsing button-theme style tag (CHARTS-371)

### PR DESCRIPTION
**Pull request by rogozinds**
"style" can't be used as a tag, changed it to "chart-style".
Add setting button-theme style to first Timeline demo.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/80)

### CODE REVIEW

**Comment by jarski** [comment]
In the ticket, it's mentioned that "In treemap-with-levels, style tag is also used and works normally". Why style works there but not inside button-theme?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-:-KBrMaKZV8L2jyJwmblx:-826983348)*

**Comment by alvarezguille** [comment]
Can we also test style inside title element?
Also check that old test pass too

---

Review status: 0 of 91 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[configuration-reader.html, line 62 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KC0XbdaW21tVEHslvV7:-KC0XbdaW21tVEHslvV8:1998291874) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9bac24b12abed0cc777cd8f4a151e1ea5cef7f06/configuration-reader.html#L62)):*
can we add quotes here?

---

*[demo/index.html, line 5 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KC0XqbXVaM5GogSTg0o:-KC0XqbYKoGmMLZaJ_Yk:1077975205) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9bac24b12abed0cc777cd8f4a151e1ea5cef7f06/demo/index.html#L5)):*
this shouldn't change

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-:-KC0_yS6PYVN5I5VdnX4:-1033694890)*

**Comment by alvarezguille** [comment]
Reviewed 85 of 90 files at r2, 5 of 6 files at r3.
Review status: 89 of 91 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFR7Au-oFNoYuy2mf1:-KCFR7Au-oFNoYuy2mf2:979372380) (no related file):*
Following files still have old tag names:
* vaadin-*-chart.html 
* binding-test.html
* chart-flexbox-size.html
* chart-reload-test.html
* pie-config-test.html

---

*[configuration-reader.html, line 49 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFLeAEL6ThmKssFLh-:-KCFLeAEL6ThmKssFLh0:-416900580) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/configuration-reader.html#L49)):*
should this change too? maybe mapping has been used when checking this

---

*[demo/timeline/single-line-series.html, line 10 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFP2renhYx31vpAQCl:-KCFP2renhYx31vpAQCm:-139564513) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/demo/timeline/single-line-series.html#L10)):*
Do we want this for the public demo?

---

*[test/chart-timeline.html, line 14 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFQ1naxhELxvri1AS2:-KCFQ1naxhELxvri1AS3:308980722) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/test/chart-timeline.html#L14)):*
This doesn't work as expected

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 90 files at r2, 14 of 15 files at r4, 26 of 26 files at r5.
Review status: 120 of 121 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[demo/line_and_scatter/spline-with-plot-bands.html, line 26 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCG3NSSsNzN1EnPxWdJ:-KCG3NSSsNzN1EnPxWdK:71891194) ([raw file](https://github.com/vaadin/vaadin-charts/blob/02c64036c97ad72a48e7eae6902c465e3e86cb96/demo/line_and_scatter/spline-with-plot-bands.html#L26)):*
chart- style?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80)*

**Comment by rogozinds** [comment]
Add style into title tag test. Fix frame and area tags to have same template.
chart-tagname. 
area-chart => chart-area
frame3d => chart-frame

---

Review status: 120 of 121 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFR7Au-oFNoYuy2mf1:-KCFaQgUnALfs4r4Mzs3:1758359675) (no related file):*
Fixed

---

*[configuration-reader.html, line 62 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KC0XbdaW21tVEHslvV7:-KCFe6AaN7ivrMp6PB4Z:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9bac24b12abed0cc777cd8f4a151e1ea5cef7f06/configuration-reader.html#L62)):*
Done.

---

*[configuration-reader.html, line 49 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFLeAEL6ThmKssFLh-:-KCFeW-tJLZAB7jz0nVP:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/configuration-reader.html#L49)):*
Done.

---

*[demo/line_and_scatter/spline-with-plot-bands.html, line 26 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCG3NSSsNzN1EnPxWdJ:-KCGC7q1Yr43PkAbq7fj:1758359675) ([raw file](https://github.com/vaadin/vaadin-charts/blob/02c64036c97ad72a48e7eae6902c465e3e86cb96/demo/line_and_scatter/spline-with-plot-bands.html#L26)):*
Fixed

---

*[demo/timeline/single-line-series.html, line 10 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFP2renhYx31vpAQCl:-KCFeyFqVitPxTCILFn7:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/demo/timeline/single-line-series.html#L10)):*
Done.

---

*[test/chart-timeline.html, line 14 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCFQ1naxhELxvri1AS2:-KCFf-d6RHUgDUDtcW9_:676635175) ([raw file](https://github.com/vaadin/vaadin-charts/blob/b126c01cfaf4f171bce851de139a077c115e3afa/test/chart-timeline.html#L14)):*
Done

---

*[demo/index.html, line 5 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KC0XqbXVaM5GogSTg0o:-KCFf4phXX_wFsFik3H9:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9bac24b12abed0cc777cd8f4a151e1ea5cef7f06/demo/index.html#L5)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-:-KCF9pDbbOk34RJcPEJ7:-597392083)*

**Comment by alvarezguille** [comment]
Review status: 120 of 121 files reviewed at latest revision, 8 unresolved discussions.

---

*[demo/line_and_scatter/spline-with-plot-bands.html, line 34 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCGCPQSIxHr_ZjAmdc_:-KCGCPQTNCsWI3b4QC_7:71891194) ([raw file](https://github.com/vaadin/vaadin-charts/blob/02c64036c97ad72a48e7eae6902c465e3e86cb96/demo/line_and_scatter/spline-with-plot-bands.html#L34)):*
chart- style?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80)*

**Comment by rogozinds** [comment]
Review status: 120 of 121 files reviewed at latest revision, 8 unresolved discussions.

---

*[demo/line_and_scatter/spline-with-plot-bands.html, line 34 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80#-KCGCPQSIxHr_ZjAmdc_:-KCGCxA9mb80b91XSV0A:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/02c64036c97ad72a48e7eae6902c465e3e86cb96/demo/line_and_scatter/spline-with-plot-bands.html#L34)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/80)*

**Pull request merged**
