### PR TITLE
Fix solid gauge demo charts-418

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/87)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Looks like demo will be running and updating even when not visible. We have other demos updating only while attached (spline-updating-each-second). Can that be replicated? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87#-:-KDNc-7vCjfi01NsaC_g:1480925004)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/other/solid-gauge.html, line 31 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87#-KDNx9WfYwxAg8D34ySQ:-KDNx9WfYwxAg8D34ySR:-316134169) ([raw file](https://github.com/vaadin/vaadin-charts/blob/de5dbd41061c1c0da23ef69e5c5f00cafab85e56/demo/other/solid-gauge.html#L31)):*
Should be defined under properties

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87)*

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/other/solid-gauge.html, line 31 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87#-KDNx9WfYwxAg8D34ySQ:-KDSBPKIgM1a5T81RmTZ:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/de5dbd41061c1c0da23ef69e5c5f00cafab85e56/demo/other/solid-gauge.html#L31)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/87)*

**Pull request merged**
