### PR TITLE
Add category-min attribute to vaadin-chart

### PR DESCRIPTION
**Pull request by DiegoCardoso**
JIRA: CHARTS-649

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/332)

### CODE REVIEW

**Comment by alexberazouski** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---

*[vaadin-chart.html, line 314 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmT9N34x26L7yfNC-C:-LAmT9N34x26L7yfNC-D:bmam0ul) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/vaadin-chart.html#L314)):*
> ```HTML
> 
>             /**
>              * Category-axis minimun value. Defaults to `undefined`.
> ```

should  be `minimum`

---

*[test/element-api-chart-test.html, line 30 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmToF44crb5B_lEzEL:-LAmToF44crb5B_lEzEM:b8f7e1s) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/test/element-api-chart-test.html#L30)):*
> ```HTML
>   <test-fixture id="category">
>     <template>
>       <vaadin-chart categries="[10,20,30]" category-min="1">
> ```

typo in categories

---

*[test/element-api-chart-test.html, line 152 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmTuWt1Up6exQ4lMGS:-LAmTuWt1Up6exQ4lMGT:b5nh2q5) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/test/element-api-chart-test.html#L152)):*
> ```HTML
>       });
> 
>       it('should have category minimun set to first category by default', (done) => {
> ```

`minimum`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332)*

**Comment by DiegoCardoso** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-chart.html, line 314 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmT9N34x26L7yfNC-C:-LAmWYcH2JrkZDOz7iN6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/vaadin-chart.html#L314)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

should  be `minimum`
</blockquote></details>

Done.

---

*[test/element-api-chart-test.html, line 30 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmToF44crb5B_lEzEL:-LAmWHmD55EfDUim-aDW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/test/element-api-chart-test.html#L30)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

typo in categories
</blockquote></details>

Done.

---

*[test/element-api-chart-test.html, line 152 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-LAmTuWt1Up6exQ4lMGS:-LAmWIc53rA0DkiBkoVw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/9d58ef852e54a5893205fb3258333251748563a6/test/element-api-chart-test.html#L152)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

`minimum`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332)*

**Comment by oluwasayo** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-:-LAmkgEYBVrJlqsIPG1l:bnfp4nl)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/332#-:-LAminvd-SkAlP84ZhKH:bnfp4nl)*

**Comment by oluwasayo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/332)*

**Pull request merged**
