### PR TITLE
Fix parsing tags values always as strings charts-276

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/86)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[configuration-reader.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUAxCH6ztH0br0jZu:-KCpUAxDkZqXOKH5evT-:-1333972167) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L185)):*
is this needed?

---

*[test/pie-config-test.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUICz-uE2bnmtNau6:-KCpUICz-uE2bnmtNau7:-2075451630) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/test/pie-config-test.html#L45)):*
don't commit this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[configuration-reader.html, line 176 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCtFFQjlWFXRksuHezn:-KCtFFQjlWFXRksuHezo:-1171317701) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L176)):*
This one is not needed, because JSON.parse("true") === true and JSON.parse('false") === false

---

*[configuration-reader.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUAxCH6ztH0br0jZu:-KCtEzL5c4AUGg7N-Ri8:-1375594769) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L185)):*
Yeah it's needed if node.textContent is just a String, then JSON.parse(content) will raise an exception

---

*[test/pie-config-test.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUICz-uE2bnmtNau6:-KCtGIgvxT1ldJqW_d6e:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/test/pie-config-test.html#L45)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[configuration-reader.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUAxCH6ztH0br0jZu:-KCtGaT7cDQMxcwH6Mdk:-1712155354) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L185)):*
but content already is node.textContent since l175

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[configuration-reader.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCpUAxCH6ztH0br0jZu:-KCtHHM_PWIMpW4ea66y:-1312502890) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L185)):*
I've removed this variable completely

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by alvarezguille** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-:-KCtNKhKYJDdZjZZKOTu:1417088721)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[configuration-reader.html, line 176 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86#-KCtFFQjlWFXRksuHezn:-KCtPJUe85SIIltoKAmu:-499146009) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6ee0aad2581741349325f58233bdfb405dd300ad/configuration-reader.html#L176)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-charts/86)*

**Pull request merged**
