### PR TITLE
Fix binding-test and chart-events-test

### PR DESCRIPTION
**Pull request by rogozinds**
Update web components tester.
Use shadowRoot in element queries.
Add setTimeout, to wait that chart object is created properly

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/154)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 3 of 10 files at r1, 1 of 1 files at r2, 2 of 4 files at r3.
Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/chart-events-test.html, line 98 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR3n-v40KXuOB3vCMK:-KhR3n-v40KXuOB3vCML:b-mc0s35) ([raw file](https://github.com/vaadin/vaadin-charts/blob/ce78302864f8a2ed70b27b975d28cbc66fb3324c/test/chart-events-test.html#L98)):*
> setTimeout(function() {

setTimeout requires done function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Comment by rogozinds** [comment]
Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/chart-events-test.html, line 98 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR3n-v40KXuOB3vCMK:-KhR4ukCQiVhL-8UbmgF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/ce78302864f8a2ed70b27b975d28cbc66fb3324c/test/chart-events-test.html#L98)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> setTimeout(function() {

setTimeout requires done function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 10 files at r1, 2 of 2 files at r4.
Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/binding-test.html, line 75 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR6tTa_w0s4N-9pXui:-KhR6tTa_w0s4N-9pXuj:b-wclyeo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/binding-test.html#L75)):*
> , 300

300 is not needed for this test

---

*[test/chart-flexbox-size.html, line 142 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7He7UXo8vlywess0:-KhR7He8c2E47w5LyuiV:bz5kuuo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L142)):*
> , 150

150 is not needed for this test

---

*[test/chart-flexbox-size.html, line 149 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7K1bffz8LcvnZghl:-KhR7K1bffz8LcvnZghm:bz5kuuo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L149)):*
> , 150

150 is not needed for this test

---

*[test/chart-flexbox-size.html, line 156 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7KgctVAL9C2Yi3x1:-KhR7KgctVAL9C2Yi3x2:bz5kuuo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L156)):*
> , 150

150 is not needed for this test

---

*[test/chart-load-event-test.html, line 99 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7O1hOo6tdMjuTKJg:-KhR7O1hOo6tdMjuTKJh:b-wclyeo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-load-event-test.html#L99)):*
> , 300

300 is not needed for this test

---

*[test/chart-reload-test.html, line 88 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7SWc3D5bsI1I03mF:-KhR7SWc3D5bsI1I03mG:b-wclyeo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-reload-test.html#L88)):*
> , 300

300 is not needed for this test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Comment by rogozinds** [comment]
Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/binding-test.html, line 75 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR6tTa_w0s4N-9pXui:-KhR8N2AkBe27mrN__Gm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/binding-test.html#L75)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 300

300 is not needed for this test
</blockquote></details>

Done.

---

*[test/chart-flexbox-size.html, line 142 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7He7UXo8vlywess0:-KhR8X_4jOOL0TvnsJYm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L142)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 150

150 is not needed for this test
</blockquote></details>

Done.

---

*[test/chart-flexbox-size.html, line 149 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7K1bffz8LcvnZghl:-KhR8X7gkq9JLXXLWyGJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L149)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 150

150 is not needed for this test
</blockquote></details>

Done.

---

*[test/chart-flexbox-size.html, line 156 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7KgctVAL9C2Yi3x1:-KhR8WvwEkQceM_KqCVi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-flexbox-size.html#L156)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 150

150 is not needed for this test
</blockquote></details>

Done.

---

*[test/chart-load-event-test.html, line 99 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7O1hOo6tdMjuTKJg:-KhR8c6wdyWreip_zcW3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-load-event-test.html#L99)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 300

300 is not needed for this test
</blockquote></details>

Done.

---

*[test/chart-reload-test.html, line 88 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhR7SWc3D5bsI1I03mF:-KhR8jX3Wkm-bBzlCL3W:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/fbf896d81cc66845800460dfb45cc53b88f6001c/test/chart-reload-test.html#L88)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> , 300

300 is not needed for this test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 5 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/chart-flexbox-size.html, line 138 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154#-KhWqe6vwKoB0OQ0d-PW:-KhWqe6vwKoB0OQ0d-PX:b-fypdle) ([raw file](https://github.com/vaadin/vaadin-charts/blob/5029122dc35afe2d5ee1eaab1fceb8a7a28ceb94/test/chart-flexbox-size.html#L138)):*
> debugger;
 remove this debugger call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/154)*

**Pull request merged**
