### PR TITLE
Fix for bar type in JSON API

### PR DESCRIPTION
**Pull request by sayo-vaadin**
Maybe not all of those references have to be changed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/218)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[vaadin-chart.html, line 363 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218#-Ky_hLZ3D8YOvBkeyj7W:-Ky_hLZ3D8YOvBkeyj7X:b-7xltex) ([raw file](https://github.com/vaadin/vaadin-charts/blob/861e59da858caafc3b6af90e579ec3a197028f04/vaadin-chart.html#L363)):*
> this.__invertForBarSeries(jsonConfiguration.series);

just a reminder, can we remove the unneeded `__invertForBarSeries` and series type override?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218)*

**Comment by alvarezguille** [comment]
*[vaadin-chart.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218#-KyaiS27qVl4Z6kFy8zK:-KyaiS28X5_INa-Kx_6D:b-i7w9ij) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4224c76c4ed393d436fcb601de3cd622bc38a7c4/vaadin-chart.html#L253)):*
> this.__internalUpdate(this.options, true, true);

if we do this we're not calling `Highcharts.chart` beforeNextRender which will cause issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218)*

**Comment by sayo-vaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart.html, line 363 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218#-Ky_hLZ3D8YOvBkeyj7W:-KyoNvmGWxFOiqQ9vv4q:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/861e59da858caafc3b6af90e579ec3a197028f04/vaadin-chart.html#L363)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> this.__invertForBarSeries(jsonConfiguration.series);

just a reminder, can we remove the unneeded `__invertForBarSeries` and series type override?
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218#-KyaiS27qVl4Z6kFy8zK:-KypTzEwDkTwq3j9tMqo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4224c76c4ed393d436fcb601de3cd622bc38a7c4/vaadin-chart.html#L253)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> this.__internalUpdate(this.options, true, true);

if we do this we're not calling `Highcharts.chart` beforeNextRender which will cause issues
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/218)*

**Pull request merged**
