### PR TITLE
CHARTS-657: Value-to-Label mapping support for vaadin-chart-series

### PR DESCRIPTION
**Pull request by oluwasayo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/299)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[chart-labels-mapper.js, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-charts/299#-L74JKMJyrYPKVOe2z2U:-L74JKMJyrYPKVOe2z2V:b-wpgf44) ([raw file](https://github.com/vaadin/vaadin-charts/blob/197a7e5b3c42fe8dc0badcc532fc45137ea20c83/chart-labels-mapper.js#L5)):*
> ```JavaScript
> 
>   constructor(mapper) {
>     const value = mapper || [];
> ```

If you take a look how `_deserializeValue` is implemented by  Polymer, they rather use a `console.warn` instead of throwing an `Error` to the user. I think we can keep the same approach here.

```javascript
_deserializeValue(value, type) {
  /**
   * @type {*}
   */
  let outValue;
  switch (type) {
    case Object:
      try {
        outValue = JSON.parse(/** @type {string} */(value));
      } catch(x) {
        // allow non-JSON literals like Strings and Numbers
        outValue = value;
      }
      break;
    case Array:
      try {
        outValue = JSON.parse(/** @type {string} */(value));
      } catch(x) {
        outValue = null;
        console.warn(`Polymer::Attributes: couldn't decode Array as JSON: ${value}`);
      }
      break;
     // [...]
  }
  return outValue;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/299)*

**Comment by oluwasayo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[chart-labels-mapper.js, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/299#-L74JKMJyrYPKVOe2z2U:-L74XVle6tKoEnfaQqtV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/197a7e5b3c42fe8dc0badcc532fc45137ea20c83/chart-labels-mapper.js#L5)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

If you take a look how `_deserializeValue` is implemented by  Polymer, they rather use a `console.warn` instead of throwing an `Error` to the user. I think we can keep the same approach here.

```javascript
_deserializeValue(value, type) {
  /**
   * @type {*}
   */
  let outValue;
  switch (type) {
    case Object:
      try {
        outValue = JSON.parse(/** @type {string} */(value));
      } catch(x) {
        // allow non-JSON literals like Strings and Numbers
        outValue = value;
      }
      break;
    case Array:
      try {
        outValue = JSON.parse(/** @type {string} */(value));
      } catch(x) {
        outValue = null;
        console.warn(`Polymer::Attributes: couldn't decode Array as JSON: ${value}`);
      }
      break;
     // [...]
  }
  return outValue;
}
```


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/299)*

**Comment by DiegoCardoso** [comment]
Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 3 files at r4.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart-series.html, line 201 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/299#-L7ANB2LvnsBk2EIlgqU:-L7ANB2LvnsBk2EIlgqV:b-u667m) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4623b8c28362d44aefa0c3c6ad6705bbc6d34c90/vaadin-chart-series.html#L201)):*
> ```HTML
>         }
> 
>         _deserializeValue(value, type) {
> ```

Please, add a `/** @private */`to this, so it won't show as protected method on the docs.

---

*[vaadin-chart-series.html, line 209 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-charts/299#-L7ANMXWOBTFZaOB4XLx:-L7ANMXWOBTFZaOB4XLy:b2nreh6) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4623b8c28362d44aefa0c3c6ad6705bbc6d34c90/vaadin-chart-series.html#L209)):*
> ```HTML
>         }
> 
>         _serializeValue(value) {
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/299)*

**Comment by oluwasayo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart-series.html, line 201 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/299#-L7ANB2LvnsBk2EIlgqU:-L7ARI2K5EPV-8F1tsYX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4623b8c28362d44aefa0c3c6ad6705bbc6d34c90/vaadin-chart-series.html#L201)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Please, add a `/** @private */`to this, so it won't show as protected method on the docs.
</blockquote></details>

Done.

---

*[vaadin-chart-series.html, line 209 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/299#-L7ANMXWOBTFZaOB4XLx:-L7ARHhq5n7aiCxlWGQz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/4623b8c28362d44aefa0c3c6ad6705bbc6d34c90/vaadin-chart-series.html#L209)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/299)*

**Pull request merged**
