### PR TITLE
fix: update DOMPurify to 2.5.7

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Update DOMPurify to the latest 2.X version.

### CODE REVIEW

**Review by web-padawan — COMMENTED** [review]
Updated `package-lock-p3.json` to keep using `"lockfileVersion": 2`.

**Review by web-padawan — COMMENTED** [review]
After converting to P3, I'm now getting errors when running `npm run generate-typings`:

```
node_modules/typescript/lib/lib.dom.d.ts:4796:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.
  Type 'HTMLElement | HTMLCanvasElement | HTMLImageElement | HTMLVideoElement | HTMLAnchorElement | ... 69 more ... | ChartElement' is not assignable to type 'Element'.
    Type 'ChartSeriesElement' is missing the following properties from type 'Element': assignedSlot, attributes, classList, className, and 123 more.

4796     getElementsByTagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/typescript/lib/lib.dom.d.ts:5169:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.
  Type 'HTMLElement | HTMLCanvasElement | HTMLImageElement | HTMLVideoElement | HTMLAnchorElement | ... 69 more ... | ChartElement' is not assignable to type 'Element'.
    Type 'ChartSeriesElement' is not assignable to type 'Element'.

5169     getElementsByTagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/typescript/lib/lib.dom.d.ts:11335:87 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Node'.
  Type 'HTMLElement | HTMLCanvasElement | HTMLImageElement | HTMLVideoElement | HTMLAnchorElement | ... 69 more ... | ChartElement' is not assignable to type 'Node'.
    Type 'ChartSeriesElement' is missing the following properties from type 'Node': baseURI, childNodes, firstChild, isConnected, and 47 more.

11335     querySelectorAll<K extends keyof HTMLElementTagNameMap>(selectors: K): NodeListOf<HTMLElementTagNameMap[K]>;
                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~
src/vaadin-chart-series.d.ts:64:42 - error TS2304: Cannot find name 'Polymer'.

64 declare class ChartSeriesElement extends Polymer.Element {
                                            ~~~~~~~
src/vaadin-chart.d.ts:29:9 - error TS2304: Cannot find name 'ChartDeepMerger'.

29 export {ChartDeepMerger};
           ~~~~~~~~~~~~~~~
src/vaadin-chart.d.ts:368:3 - error TS2416: Property 'title' in type 'ChartElement' is not assignable to the same property in base type 'PolymerElement'.
  Type 'string | null | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

368   title: string|null|undefined;
      ~~~~~
```

Looks like it's caused by `declare class ChartSeriesElement extends Polymer.Element` in `vaadin-chart-series.d.ts`

**Comment by DiegoCardoso** [comment]
This error seem to be reproducible in `master` as well. Any idea what it could be?

**Comment by web-padawan** [comment]
Nevermind, in V14 we don't publish `.d.ts` for `vaadin-charts` e.g. I couldn't find them when installing `v6.3.7`.

**Review by web-padawan — APPROVED** [review]
LGTM. Probably could mark this as `fix:` to indicate it's actually a fix in release notes.

**Pull request merged**
