### PR TITLE
Add support for events

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Create function callbacks to dispatch custom events for Highcharts supported events list on chart, series and point levels.

JIRA: CHARTS-691

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/235)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-chart.html, line 523 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGJatFgCd5Ctpx_XK:-L-HGJauQ2Cz_3g56iKr:b1hxjox) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/vaadin-chart.html#L523)):*
> ```HTML
>           const eventObject = this.__ensureObjectPath(configuration, pathToAdd);
> 
>           for (let keys = Object.keys(eventList), i = 0; i < keys.length; i++) {
> ```

Can be replaced with `Object.keys(eventList).forEach(key => {`. Also removes the need for the next line.

---

*[demo/index.html, line 137 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGefI0ZwQIPj2S_Qj:-L-HGefI0ZwQIPj2S_Qk:b-kr2j44) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L137)):*
> ```HTML
> 
>     <h3>Adding event listeners <small>(Try clicking at chart background and any series point)</small></h3>
>     
> ```

Trailing whitespace

---

*[demo/index.html, line 160 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGd1GAaG77Sk5369F:-L-HGd1GAaG77Sk5369G:b-kr2j44) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L160)):*
> ```HTML
>                 super.connectedCallback();
>                 this.$.mychart.addEventListener('point-click', (event) => {
>                   alert('[EVENT: POINT-CLICK] You can add events with addEventListener.');                  
> ```

Trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGd8VljKxA90X9Zfm:-L-HGd8VljKxA90X9Zfn:but17ng) (no related file):*
Should we have a minimal list of available events with jsdoc for them? Class level jsdoc maybe?

---

*[demo/index.html, line 160 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGzCDEsGsaG7YEK-M:-L-HGzCDEsGsaG7YEK-N:b-buxjwt) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L160)):*
>                   alert('[EVENT: POINT-CLICK] You can add events with addEventListener.');··················

Showing some of the info of the event would make this a more complete dem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by DiegoCardoso** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGd8VljKxA90X9Zfm:-L-VmyeOc37IbkmNkrB9:b-vbskjw) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Should we have a minimal list of available events with jsdoc for them? Class level jsdoc maybe?
</blockquote></details>

Added jsdoc for events. I couldn't make the documentation for events params work, though.

---

*[vaadin-chart.html, line 523 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGJatFgCd5Ctpx_XK:-L-HRRiHZWPckx0gA-8S:bozyln3) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/vaadin-chart.html#L523)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Can be replaced with `Object.keys(eventList).forEach(key => {`. Also removes the need for the next line.
</blockquote></details>

That's true. But I think that adding as `forEach` adds a bit of overhead as it needs to call a function for every loop. So it's a bit faster doing this way.

---

*[demo/index.html, line 137 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGefI0ZwQIPj2S_Qj:-L-VnJGkM_I5SnisOFmP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L137)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.

---

*[demo/index.html, line 160 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGzCDEsGsaG7YEK-M:-L-VnERl5wRrID7kSQRz:be3vkdv) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L160)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>                   alert('[EVENT: POINT-CLICK] You can add events with addEventListener.');··················

Showing some of the info of the event would make this a more complete dem
</blockquote></details>

Changed to add a better UI, as suggested.

---

*[demo/index.html, line 160 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGd1GAaG77Sk5369F:-L-VnlGG3UbQzU3lOuxR:bcjtrey) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L160)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Removed the previous code when the comment was made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 4 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by alvarezguille** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 137 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235#-L-HGefI0ZwQIPj2S_Qj:-L-a9UXrE11qOqTrURi3:b32wqo) ([raw file](https://github.com/vaadin/vaadin-charts/blob/1b3b89bff5e060bf9a1f9fd7f1acf5af21023f67/demo/index.html#L137)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

lg

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/235)*

**Pull request merged**
