### PR TITLE
CHARTS-760: Chart should be usable as a virtual child

### PR DESCRIPTION
**Pull request by oluwasayo**
- Ensure charts can accept configuration updates even when not connected (essential for supporting chart-flow as a virtual child)
- Ensure that all buffered updates are applied when connected
- Drop dirty checking since we now buffer changes

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/309)

### CODE REVIEW

**Comment by oluwasayo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 370 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8IQONOJTEc9y87LHSh:-L8IW1db4xO-szvDtPmv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/93527289ffcd6616eb9809c57da69a213b6c278b/vaadin-chart.html#L370)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

You don't need to split it. `Object.assign` will ignore if `this._jsonConfigurationBuffer` is `null`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[vaadin-chart.html, line 370 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEsrsCJfOt3jiKBkN:-L8WEsrsCJfOt3jiKBkO:bm0wnxl) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L370)):*
> ```HTML
>             }
> 
>             const options = Object.assign({}, this.options, this._jsonConfigurationBuffer);
> ```

Do you think that `_jsonConfigurationBuffer` should be cleared after used here?

---

*[vaadin-chart.html, line 721 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEBjp503RCEfkPzR2:-L8WEBjp503RCEfkPzR3:b63r862) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L721)):*
> ```HTML
>           this._jsonConfigurationBuffer = this.__makeConfigurationBuffer(this._jsonConfigurationBuffer, jsonConfiguration);
>           if (this._jsonConfigurationBuffer) {
>             this.__inflateFunctions(this._jsonConfigurationBuffer);
> ```

Why is it now inflating the buffer for every call to `update`.  Doesn't it affect the performance in case of multiple calls before next render?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309)*

**Comment by oluwasayo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-chart.html, line 370 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEsrsCJfOt3jiKBkN:-L8WFP_sCajjG9-DXN8M:b-mz9ed9) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L370)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Do you think that `_jsonConfigurationBuffer` should be cleared after used here?
</blockquote></details>

Clearing the buffer or not has no effect on correctness, although there might be a little performance benefit in doing so (i.e less JSON configuration data for HighCharts to process in the next `update` call).

I will make this change shortly.

---

*[vaadin-chart.html, line 721 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEBjp503RCEfkPzR2:-L8WFoV0EiaxRMosIRqo:b-no09n4) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L721)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Why is it now inflating the buffer for every call to `update`.  Doesn't it affect the performance in case of multiple calls before next render?
</blockquote></details>

The buffer was also previously being inflated every time, only that it was being done before next render. The `__inflateFunctions` function deletes inflated properties from the JSON tree so they are not reinflated every time, however there might be a little performance benefit in inflating just the `jsonConfiguration` parameter since that JSON tree cannot be larger than the buffer so there's less data to traverse.

I will make this change shortly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309)*

**Comment by oluwasayo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-chart.html, line 370 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEsrsCJfOt3jiKBkN:-L8WK59c4Y5XYAZDBOzd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L370)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

Clearing the buffer or not has no effect on correctness, although there might be a little performance benefit in doing so (i.e less JSON configuration data for HighCharts to process in the next `update` call).

I will make this change shortly.
</blockquote></details>

Done.

---

*[vaadin-chart.html, line 721 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEBjp503RCEfkPzR2:-L8WKzcO5fxKHbsRiCGG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L721)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

The buffer was also previously being inflated every time, only that it was being done before next render. The `__inflateFunctions` function deletes inflated properties from the JSON tree so they are not reinflated every time, however there might be a little performance benefit in inflating just the `jsonConfiguration` parameter since that JSON tree cannot be larger than the buffer so there's less data to traverse.

I will make this change shortly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 721 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309#-L8WEBjp503RCEfkPzR2:-L8WWAjdBR4JUJvHLANh:b-ka082d) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L721)):*
Do you think is there any benefits for also not traverse the whole JSON tree for every call? 

> [...] since that JSON tree cannot be larger than the buffer so there's less data to traverse

I believe this assumption is not always correct:
1. Think about the first call to `update` with only `title` and a second call with `series`, `xAxis` and so on.
2. Also, in the process of multiple calls to `update`, it may occur that some configuration overrides the previous one, which may lose some inflated functions.

I know that this is also something that may not happen often, as the usual use case is to send one configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309)*

**Comment by oluwasayo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 721 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309#-L8WEBjp503RCEfkPzR2:-L8Womlp7RT8gsDJi40R:b-o50ho8) ([raw file](https://github.com/vaadin/vaadin-charts/blob/efdf1248212c829778d06248ed078d09444a8752/vaadin-chart.html#L721)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Do you think is there any benefits for also not traverse the whole JSON tree for every call? 

> [...] since that JSON tree cannot be larger than the buffer so there's less data to traverse

I believe this assumption is not always correct:
1. Think about the first call to `update` with only `title` and a second call with `series`, `xAxis` and so on.
2. Also, in the process of multiple calls to `update`, it may occur that some configuration overrides the previous one, which may lose some inflated functions.

I know that this is also something that may not happen often, as the usual use case is to send one configuration.

</blockquote></details>

Result of 1:1 discussion:

1. Not valid. `update` parameter is always merged into the buffer so a parameter cannot be larger than the buffer as we had it before this change.
2. This is a valid concern. However, it's a known tradeoff for situations where a connection of the element occurs between the time `update` is called and the time `beforeNextRender` runs. In those situations the buffer would be applied in `connectedCallback` without inflating the functions, something we want to avoid.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-charts/309)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 735 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309#-L8X1eUdp3w0tDSrZOa2:-L8X1eUdp3w0tDSrZOa3:b-q7jtr8) ([raw file](https://github.com/vaadin/vaadin-charts/blob/8791848285b5976951261773d479eaef902881ac/vaadin-chart.html#L735)):*
> ```HTML
>             this._jsonConfigurationBuffer = {};
>           }
>           const configCopy = this.__deepMerge({}, jsonConfiguration);
> ```

As this is only merging with an empty object, I think it would make more sense to use `Object.assign` instead, as it for being native may be a bit faster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309)*

**Comment by oluwasayo** [comment]
*[vaadin-chart.html, line 735 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309#-L8X1eUdp3w0tDSrZOa2:-L8X21NIsxGUyi_TxD0C:b-clyvu8) ([raw file](https://github.com/vaadin/vaadin-charts/blob/8791848285b5976951261773d479eaef902881ac/vaadin-chart.html#L735)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

As this is only merging with an empty object, I think it would make more sense to use `Object.assign` instead, as it for being native may be a bit faster.
</blockquote></details>

The issue with `Object.assign` is that it does a shallow copy. If the input is the following for example: 
```{
  xAxis: {
    events: {
      _fn_setExtremes: "function(event) { alert('stuff'); }"
    }
  }
}```

`Object.assign` only copies a reference to `xAxis` to the empty object and `__inflateFunction` will modify that. I'm not sure if it's okay to modify the input.
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 735 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309#-L8X1eUdp3w0tDSrZOa2:-L8X5WFY4fICC5cPiCXk:bvtqi5p) ([raw file](https://github.com/vaadin/vaadin-charts/blob/8791848285b5976951261773d479eaef902881ac/vaadin-chart.html#L735)):*
<details><summary><i>Previously, oluwasayo (Sayo Oladeji) wrote…</i></summary><blockquote>

The issue with `Object.assign` is that it does a shallow copy. If the input is the following for example: 
```{
  xAxis: {
    events: {
      _fn_setExtremes: "function(event) { alert('stuff'); }"
    }
  }
}```

`Object.assign` only copies a reference to `xAxis` to the empty object and `__inflateFunction` will modify that. I'm not sure if it's okay to modify the input.
</blockquote></details>

That's true. It's not ok to modify user's input, so `__deepMerge` does a better job here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309)*
<!-- Sent from Reviewable.io -->

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/309#-:-L8a3xsgK9JXrRINuPye:bnfp4nl)*

**Pull request merged**
