### PR TITLE
Add API allowing function calls on chart, axis, series and point level

### PR DESCRIPTION
**Pull request by alvarezguille**
This API is not public, but might be used by a server-side component

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-charts/232)

### CODE REVIEW

**Comment by sayo-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 562 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232#-L-6GLfNa-6k3S-NzUeF:-L-6GLfNa-6k3S-NzUeG:bwhauqh) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6d9f621adb8c149f23191c997910ce43f632a8b1/vaadin-chart.html#L562)):*
> ```HTML
>                 axes = this._configuration.colorAxis;
>                 break;
>               default:
> ```

Is this needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232)*

**Comment by sayo-vaadin** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232)*

**Comment by alvarezguille** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-chart.html, line 562 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232#-L-6GLfNa-6k3S-NzUeF:-L-6euSvZR8s9k_1T7dv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-charts/blob/6d9f621adb8c149f23191c997910ce43f632a8b1/vaadin-chart.html#L562)):*
<details><summary><i>Previously, sayo-vaadin (Sayo Oladeji) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232)*

**Comment by sayo-vaadin** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-charts/232)*

**Pull request merged**
